remote_theme: pages-themes/slate@v0.2.0
plugins:
  - jekyll-remote-theme

title: AQIS2024 Satellite Workshop on Fault-Tolerant Quantum Computing
description: Bridging quantum error correction, computer architecture, network, and device engineering on Aug. 31st, 2024 in Sapporo, Japan

downloads: "false"
