remote_theme: pages-themes/slate@v0.2.0
plugins:
  - jekyll-remote-theme

title: AQIS2024 satellite workshop
description: bridging quantum error correction, computer architecture, network, and device engineering on Aug. 31st, 2024 @ TBA

downloads: "false"
